//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabiticaHourUpVSIX.AppSettings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class HabiticaSettings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static HabiticaSettings1 defaultInstance = ((HabiticaSettings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HabiticaSettings1())));
        
        public static HabiticaSettings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalTicks {
            get {
                return ((int)(this["TotalTicks"]));
            }
            set {
                this["TotalTicks"] = value;
            }
        }
    }
}
