//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabiticaHourUpVSIX.AppSettings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class UserSettings3 : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSettings3 defaultInstance = ((UserSettings3)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettings3())));
        
        public static UserSettings3 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01:00:00")]
        public global::System.TimeSpan Divisor {
            get {
                return ((global::System.TimeSpan)(this["Divisor"]));
            }
            set {
                this["Divisor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TaskIDToScoreUp {
            get {
                return ((string)(this["TaskIDToScoreUp"]));
            }
            set {
                this["TaskIDToScoreUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoScoreUp {
            get {
                return ((bool)(this["IsAutoScoreUp"]));
            }
            set {
                this["IsAutoScoreUp"] = value;
            }
        }
    }
}
