// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HabiticaHourUpVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "HabiticaHourUpVSIX.ade8e5f3-585d-49ca-8916-064b2237b928";
        public const string Name = "HabiticaHourUpVSIX";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.3.0";
        public const string Author = "Ar6";
        public const string Tags = "";
    }
}
